[package]
name = "pust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigint = { version = "0.4" }
num-traits = { version = "0.2.14" }
clap = { version = "3.1.6", features = ["derive"] }